env:
  global:
    - SHA=$TRAVIS_PULL_REQUEST_SHA
    - TIMEOUT=1000
jobs:
  include:
    - stage: first
      script: python3 -u script.py
      after_script: bash deploy.sh
#     - stage: second
#       language: python
#       python: "3.6"
#       cache: pip
#       install: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
#       script: python3 -u bad_script.py
#     - stage: third
#       language: python
#       python: "3.6"
#       cache: pip
#       install: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
#       script: python3 -u script.py
#     - stage: fourth
#       language: python
#       python: "3.6"
#       cache: pip
#       install: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
#       script: python3 -u bad_script.py
